image: maven:3.6.3-openjdk-11

stages:
  - validate
  - build
  - test
  - visualize

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode --errors --fail-at-end"

cache:
  paths:
    - ./.m2/repository/

compile:
  tags:
    - docker
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS compile'  
  artifacts:
    expire_in: 10 min
    paths: 
      - target/ 
      - '*/target'

junit:
  tags:
    - docker
  stage: test
  script:
    - find . -name "*.class" -exec touch {} \+
    - 'mvn $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report'
  artifacts:
    when: always
    paths:
        - './target/site/jacoco/jacoco.xml'
    reports:
      junit:
        - './target/surefire-reports/TEST-*.xml'

coverage:
  # Must be in a stage later than test-jdk11's stage.
  # The `visualize` stage does not exist by default.
  # Please define it first, or chose an existing stage like `deploy`.
  stage: visualize
  tags:
    - docker
  image: haynes/jacoco2cobertura:1.0.4
  script:
    # convert report from jacoco to cobertura
    - 'python /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java > target/site/cobertura.xml'
    # read the <source></source> tag and prepend the path to every filename attribute
    - 'python /opt/source2filename.py target/site/cobertura.xml'
  needs: ["junit"]
  dependencies:
    - junit
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml        

validate:
  tags:
    - docker
  stage: validate
  script:
    - 'mvn $MAVEN_CLI_OPTS validate'

checkstyle:
  tags:
    - docker
  stage: validate
  script:
    - 'mvn $MAVEN_CLI_OPTS checkstyle:check'
  allow_failure: true